# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- powershell: |
  env:
    SCD_Access: $(GitHubPAT) # the recommended way to map to an env variable

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
